### ISSUE TITLE
Performance results 

### ISSUE THREAD

**Issue by abhigoku10** [yasenh/sort-cpp#1]
@yasenh thanks for wonderful source code , i had few quereis 

1. the performance results are low compared to https://github.com/mcximing/sort-cpp
2. is this the similar implementation or different
3. what all fine tuning has to be done in the code 
4. will this work 3d object tracking also 

Thanks in advance

**Comment by yasenh** [comment]
@abhigoku10 
1. The degrade dperformance may because that I track the width and height of bounding box instead of the scale (s) and aspect ratio(r). I will try different parameters in next few days.
2. For 3d tracking, the basic concept could be the same, but you need to add some more states (e.g. z dimension).

**Comment by abhigoku10** [comment]
@yasenh thanks for the response eagerly waiting for the fixes , i am trying to convert ur current code with 3D tracking will have few queries going on

**Comment by yasenh** [comment]
@abhigoku10 Try to pull the latest commits

**Comment by abhigoku10** [comment]
@yasenh are we obtaining the constant velocity also with ur current implementation ??

**Comment by yasenh** [comment]
> @yasenh are we obtaining the constant velocity also with ur current implementation ??

Yes, it is contant velocity model, as the same as the implementation from Python version. You could consider CTRV or CTRA model for 3D tracking.

**Comment by abhigoku10** [comment]
@yasenh any plans of making this source code for 3D tracking also ?? if so what is the estimated time line https://github.com/xinshuoweng/AB3DMOT this is sota for 3D tracking

**Comment by yasenh** [comment]
> @yasenh any plans of making this source code for 3D tracking also ?? if so what is the estimated time line https://github.com/xinshuoweng/AB3DMOT this is sota for 3D tracking

Maybe at the end of this year LOL
