### ISSUE TITLE
Oriented object tracking 

### ISSUE THREAD

**Issue by abhigoku10** [yasenh/sort-cpp#2]
@yasenh  can this source code track objects having orientation ?? if not where can i add the orientation of the object parameters ??

**Comment by yasenh** [comment]
> @yasenh can this source code track objects having orientation ?? if not where can i add the orientation of the object parameters ??

The orientation is not tracked at this point, and the state is (x, y, width, length, vx, vy, v_width, v_length). If you want to track 3D bbox, you need to modify the states to (x, y, z, width, length, height, yaw, vx, vy, vz, v_width, v_length, v_height, yaw_rate), and the way to calcuate IoU also need to be updated accordingly.

**Comment by yasenh** [comment]
> @yasenh thanks for the pointers , i want to track objects which have orientation in 2D image only the example is given below
> ![image](https://user-images.githubusercontent.com/22094053/67863386-d36f9380-fb49-11e9-80a1-e5b1dab5aac7.png)

Yes, you could track the orientation of 2D bounding box as well. But like I mentioned before, you need to update:
1. The states of tracker
2. The IoU calcuation
